apiVersion: v1
kind: Service
metadata:
  name: woongkie-talkie
  namespace: woongkie-talkie
  labels:
    app.kubernetes.io/name: woongkie-talkie
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: woongkie-talkie
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
